src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>is_Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>is Primary</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/opportunityHandler.cls
public class opportunityHandler {
    public static void updateRelatedPrimaryContact(List<opportunity> oppLst , Map<id,opportunity> oldOpptyMap, Map<id,Opportunity> newOptyMap){
        Set<id> relatedAccountIds = new Set<id>();
        
        if(!oppLst .isEmpty()){
            for(opportunity opp : oppLst){
                relatedAccountIds.add(opp.accountId);
            }
            if(!relatedAccountIds.isEmpty()){
                Map<id,account> accoutMap = new Map<id,account>([Select id,(select id,is_Primary__c from contacts where is_Primary__c=: true) from account]);
                for(opportunity opp : oppLst){
                    List<contact> conLst = accoutMap.get(opp.accountId).contacts;
                    system.debug('++ get related account and contact details ++++ '+accoutMap.get(opp.accountId)+' +++ conLst ++'+conLst.size());
                    if(conLst.size() > 0){
                        opp.Primary_contact__c = conLst[0].id;
                    }else{
                        opp.addError(system.label.isPrimaryCheckError);
                    }
                }
            }        
       }
    }
}