src/objects/Outlet__c.object
<CustomObject>
    <description>Collects all the outlets information from the system.</description>
    <fields>
        <fullName>Outlet_Owner_Email__c</fullName>
        <label>Outlet Owner Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Retail_Shop__c</fullName>
        <label>Retail Shop Name</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Retail_Shop__c.Country__c</field>
                <operation>equals</operation>
                <valueField>$Source.Country__c</valueField>
            </filterItems>
            <filterItems>
                <field>Retail_Shop__c.State__c</field>
                <operation>equals</operation>
                <valueField>$Source.State__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Retail_Shop__c</referenceTo>
        <relationshipLabel>Outlets</relationshipLabel>
        <relationshipName>Outlets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Outlet</label>
    <nameField>
        <label>Outlet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Outlets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Retail_Shop__c.object
<CustomObject>
    <description>Retail Store details</description>
    <fields>
        <fullName>Retail_Shop_Owner__c</fullName>
        <label>Retail Shop Owner</label>
        <type>Email</type>
    </fields>
    <label>Retail Shop</label>
    <nameField>
        <label>Retail Shop Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retail Shops</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/sendingEmailThroughOutlet.cls
public class sendingEmailThroughOutlet {
    public static void sendEmilToRetailStoreOwnerFromOutlet(List<Outlet__c> newOutletLst , Map<id,Outlet__c> oldOutletMap , Map<id,Outlet__c> newOUtletMap){
        set<id> retailStoreIds = new Set<id>();
        for(Outlet__c outLet:newOutletLst ){
            if(outLet.Retail_Shop__c != null){
                retailStoreIds.add(outLet.Retail_Shop__c);
            }
        }
        if(!retailStoreIds.isEmpty()){
            Map<id,Retail_Shop__c> retailStoreMap = new Map<id,Retail_Shop__c>([Select id,Retail_Shop_Owner__c from Retail_Shop__c where id IN:retailStoreIds]);
            for(Outlet__c outLet:newOutletLst ){
                Messaging.singleEmailMessage mail = new Messaging.singleEmailMessage();
                List<string> toAddresses = new List<string>();
                toAddresses.add(retailStoreMap.get(outLet.Retail_Shop__c).Retail_Shop_Owner__c);
                toAddresses.add(outLet.Outlet_Owner_Email__c);
                mail.setToAddresses(toAddresses);
                mail.setSubject('Send an email Test');
                string template = 'test the Template \n jsvjcvsjvdjsd \n';
                template += 'test Subject 123';
                List<string> args = new List<string>();
                args.add(outLet.Name);
                string formattedHtml = string.format(template,args);
                mail.setPlainTextBody(formattedHtml);
                Messaging.sendemail(new Messaging.singleEmailMessage[]{mail});
            }
        }    
    }
}